image: qdata/qciagent:Master-Ubuntu18

pipelines:
  branches:
    stage:
      - step:
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3 # required for codedeploy_deploy.py
            - npm install
            #- bower install --allow-root
            - npm run build --prod
            - chmod +x scripts/*
            - export DEPLOYMENT_GROUP_NAME=$STAGE_DEPLOYMENT_GROUP_NAME
            - zip -r /tmp/artifact.zip * # package up the application for deployment
            - python codedeploy_deploy.py # run the deployment script

    hub-stage:
      - step:
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3 # required for codedeploy_deploy.py
            - npm install
            #- bower install --allow-root
            - npm run build --prod
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export S3_BUCKET=$S3_BUCKET_STAGE
            - export LC_ALL=en_US.UTF-8
            - aws s3 sync . s3://$S3_BUCKET_STAGE/website --acl public-read --delete  --region $REGION #Deploy in S3
    
    hub-pro:
      - step:
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3 # required for codedeploy_deploy.py
            - npm install
            #- bower install --allow-root
            - npm run build -- --prod
            - grep -Rl '8.2.14' dist/hub-contenidos-front/ | xargs -I {} sed -i 's/8.2.14/Unknown/g' {}
            - cd dist/hub-contenidos-front/
            #- export DEPLOYMENT_GROUP_NAME=$PRO_DEPLOYMENT_GROUP_NAME
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export S3_BUCKET=$S3_BUCKET_PRO
            #- export APPLICATION_NAME=$APPLICATION_NAME_PRO
            - export LC_ALL=en_US.UTF-8
            #- zip -r /tmp/artifact.zip * # package up the application for deployment
            #- python codedeploy_deploy.py # run the deployment script
            - aws s3 sync . s3://$S3_BUCKET_PRO/website --acl public-read --delete  --region $REGION #Deploy in S3
