#!/bin/bash
#cp -R /tmp/hub-contenidos-website/dist/hub-contenidos-front/* /home/ubuntu/hub-contenidos-publicwebsite/
sudo find /tmp/hub-contenidos-website/dist/hub-contenidos-front/ -type f -empty -delete
sudo aws s3 cp /tmp/hub-contenidos-website/dist/hub-contenidos-front s3://testhub.qdata.io/website/  --recursive
